### ISSUE TITLE
Names are not hidden behind barriers

### ISSUE THREAD

**Issue by Kogomre** [pitbox46/HiddenNames#3]
Hi, the player tag is visible behind obstacles, but is not visible when the player is nearby, how can i hide this?
![Screenshot_1](https://github.com/pitbox46/HiddenNames/assets/43267690/765bcf1b-ac52-4c39-8a12-9db942e3e7f8)

**Comment by pitbox46** [comment]
What version of the mod are you using?

**Comment by Kogomre** [comment]
@pitbox46 Hiddennames-1.20.1-1.0.0.jar

**Comment by Ranciddusty79** [comment]
[Eileen Voyles](url)

**Comment by Kogomre** [comment]
@pitbox46 hiddennames-1.20.1-1.0.1.jar have this problem too, do you think about fix it?

**Comment by pitbox46** [comment]
I haven't been able to reproduce this issue. Are you using mods other than HiddenNames?

**Comment by Kogomre** [comment]
@pitbox46 how can i test this without another player?

**Comment by pitbox46** [comment]
I'm not sure there's a way to do so. I open two instances and use LAN

**Comment by Kogomre** [comment]
@pitbox46 i found problem, this is conflict with mod Entityculling-forge-1.6.2-mc1.20.1.jar, when he install i have this bug, maybe this help you to fix this? Thx.

**Comment by pitbox46** [comment]
I think there might be a config option called `renderNametagsThroughWalls` for that mod. Note that the animations will *not* show for culled entities if you are deciding to render names through the walls due to some other compatibility stuff I found in their code.

**Comment by Kogomre** [comment]
@pitbox46 i test it later, but now i remove this mod and use Embendium Plus entity culling and its working good, i think if you don't make fix, write this in description mod, for help other people)
