### ISSUE TITLE
java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by AqueleHaru** [pitbox46/HiddenNames#5]
https://mclo.gs/LAdUsVj

**Comment by AqueleHaru** [comment]
and crash the server.

**Comment by pitbox46** [comment]
Not sure what happened here. Looks like your data file is corrupted or something. I would recommend deleting the hiddennames.json file in the hiddennames folder in the world save

**Comment by AqueleHaru** [comment]
its almost like a bug from fakename, if i set fakename with colors, it changes the & and § to �.

<img width="319" alt="image" src="https://github.com/pitbox46/HiddenNames/assets/61639486/9d2749bb-404b-4a72-86a5-b8e10072d9c2">

**Comment by pitbox46** [comment]
Hmm, I will look into this

**Comment by AqueleHaru** [comment]
any uipdate?

**Comment by pitbox46** [comment]
I am very confused. Why would you have Hiddennames and Fakename? They do about the same thing
