### ISSUE TITLE
data.json reset

### ISSUE THREAD

**Issue by willis1030** [pitbox46/HiddenNames#6]
Server: NeoForge-1.20.1-47.1.88
Client: NeoForge-1.20.1-47.1.96
mods: hiddennames-1.20.1-1.0.0.jar

I have edited the file ..\world\hiddennames\data.json
I guess if there is some special word like this:
"text": "§6中文-§fs97"
after server stop and restart, the file data.json has been reset to empty.

**Comment by willis1030** [comment]
when I leave server and re-enter the server, the "suggest_command" has reset to /tell

**Comment by willis1030** [comment]
Sorry I found Forge Server is ok! The problem happened in NeoForge.

**Comment by pitbox46** [comment]
Hmm, it's probably a compat issue with NeoForge for 1.20.1 then. Unless you find similar problems in the 1.20.4 NeoForged version or the 1.20.1 Forge version, I will close this issue.
