### ISSUE TITLE
Modified suggest_command only effects on displayName

### ISSUE THREAD

**Issue by willis1030** [pitbox46/HiddenNames#7]
Server: Forge 1.20.1-47.2.20
Client: Forge 1.20.1-47.2.20
mod: hiddennames-1.20.1-1.0.0

I have modefied the "suggest_command" to /tpa in data.json file, but it only effects on displayName after chat, others messages like killing by zombies will show default as /tell.
is that a bug?

**Comment by pitbox46** [comment]
Could you post your `data.json`? You can use something like https://pastebin.com/

**Comment by willis1030** [comment]
my data.json is like this below:

[
  {
    "uuid": "89677e38-3c0b-47dd-9b53-4991fcc9439e",
    "displayName": {
      "insertion": "willis97",
      "clickEvent": {
        "action": "suggest_command",
        "value": "/tpa willis97 "
      },
      "hoverEvent": {
        "action": "show_entity",
        "contents": {
          "type": "minecraft:player",
          "id": "89677e38-3c0b-47dd-9b53-4991fcc9439e",
          "name": {
            "text": "willis97"
          }
        }
      },
      "text": "willis97"
    },
    "animation": "null"
  }
]

and the message is like this:
![20240204 062848](https://github.com/pitbox46/HiddenNames/assets/16789564/747bed03-c063-48f6-9a0b-2f199c1cb3e3)

left click on the name of first message:
![20240204 062908](https://github.com/pitbox46/HiddenNames/assets/16789564/7785c234-63b5-4328-a027-c968301888ff)
command is /tpa
but left click on the name of kill by creeper message:
![20240204 062929](https://github.com/pitbox46/HiddenNames/assets/16789564/9c31e465-075d-4d60-81fe-835ea67a5db8)
command is /tell

This time, I use hiddennames mod as the only mod in server and client.

**Comment by pitbox46** [comment]
Thank you, I will look into this

**Comment by pitbox46** [comment]
Fixed. A new version will be up on CurseForge soon

**Comment by willis1030** [comment]
Thank you for such a quick response, but this time, modify the "suggest_command" became not working.
I modified it to "/tpa" but it shows "/tell" everywhere.

**Comment by pitbox46** [comment]
I'm not having this problem at all. I'm closing the server, modifying the data.json clickEvent value to be `/tp Dev` and it works after I start the server up again. Seems to work fine after closing the server and starting it again as well for me.

**Comment by willis1030** [comment]
https://github.com/pitbox46/HiddenNames/assets/16789564/6805818d-d7e7-4c48-bd3f-150cb5055dd7



https://github.com/pitbox46/HiddenNames/assets/16789564/8a3eb9ea-025b-404d-a8c2-771090eb551a


Because of 10mb limit, I split into 2 videos.
It is not working for me.

**Comment by willis1030** [comment]
https://github.com/pitbox46/HiddenNames/assets/16789564/c37e0827-f0ee-4a69-8546-576ece77fc28

re-upload for another video.

**Comment by willis1030** [comment]
This is my enviroment:
Server: Forge 1.20.1-47.2.20
Client: Forge 1.20.1-47.2.20
mod: hiddennames-1.20.1-1.0.1

Windows10
Client: java8update401 (1.8.0_401)
Server: jdk-18.0.2.1

**Comment by pitbox46** [comment]
I've found the issue. I'll have a fix up soon
