### ISSUE TITLE
Data.json reset

### ISSUE THREAD

**Issue by MechRW** [pitbox46/HiddenNames#8]
ok,man. i test this 
core:arclight-forge-1.20.1-1.0.5-SNAPSHOT
forge:forge-1.20.1-47.2.20-installer

this is Really funny that if i set player names in English,is works and not reset when i restart my severs.
BUT when i SET NAMES IN Chinese,it reset. i really confused.

IDK this is your bug or this is arclight's bug. may you fix it please?

**Comment by pitbox46** [comment]
I will look into this, likely is an issue with the character encoding. Could replicate the issue and provide the latest logs?

**Comment by pitbox46** [comment]
Also can you direct me to the page for arclight? I'm not exactly sure what it is

**Comment by MechRW** [comment]
ok,man,wait a min, i will send this error of hiddennames in my latest.log.
looks like String error of UTF-8

> [084月2024 00:01:47.988] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Input length = 1
> 	Index: 3
> 	Listeners:
> 		0: NORMAL
> 		1: net.minecraftforge.eventbus.EventBus$$Lambda$4297/0x0000000801784c78@3e413057
> 		2: ASM: github.pitbox46.fightnbtintegration.FightNBTIntegration@6082c9c3 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
> 		3: ASM: class github.pitbox46.hiddennames.ServerEvents onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
> java.nio.charset.MalformedInputException: Input length = 1
> 	at java.base/java.lang.String.throwMalformed(String.java:1240)
> 	at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1191)
> 	at java.base/java.lang.String.newStringUTF8NoRepl(String.java:728)
> 	at java.base/java.lang.String.newStringNoRepl1(String.java:756)
> 	at java.base/java.lang.String.newStringNoRepl(String.java:738)
> 	at java.base/java.lang.System$2.newStringNoRepl(System.java:2390)
> 	at java.base/java.nio.file.Files.readString(Files.java:3369)
> 	at java.base/java.nio.file.Files.readString(Files.java:3325)
> 	at TRANSFORMER/hiddennames@1.20.1-1.0.2/github.pitbox46.hiddennames.JsonData.readToData(JsonData.java:43)
> 	at TRANSFORMER/hiddennames@1.20.1-1.0.2/github.pitbox46.hiddennames.ServerEvents.onServerStarting(ServerEvents.java:25)
> 	at TRANSFORMER/hiddennames@1.20.1-1.0.2/github.pitbox46.hiddennames.__ServerEvents_onServerStarting_ServerStartingEvent.invoke(.dynamic)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 	at TRANSFORMER/forge@47.2.20/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:110)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:201)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 
> [084月2024 00:01:47.988] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> java.nio.charset.MalformedInputException: Input length = 1
> 	at java.lang.String.throwMalformed(String.java:1240) ~[?:?] {re:mixin}
> 	at java.lang.String.decodeUTF8_UTF16(String.java:1191) ~[?:?] {re:mixin}
> 	at java.lang.String.newStringUTF8NoRepl(String.java:728) ~[?:?] {re:mixin}
> 	at java.lang.String.newStringNoRepl1(String.java:756) ~[?:?] {re:mixin}
> 	at java.lang.String.newStringNoRepl(String.java:738) ~[?:?] {re:mixin}
> 	at java.lang.System$2.newStringNoRepl(System.java:2390) ~[?:?] {}
> 	at java.nio.file.Files.readString(Files.java:3369) ~[?:?] {re:mixin}
> 	at java.nio.file.Files.readString(Files.java:3325) ~[?:?] {re:mixin}
> 	at github.pitbox46.hiddennames.JsonData.readToData(JsonData.java:43) ~[hiddennames-1.20.1-1.0.2.jar%23205!/:1.20.1-1.0.2] {re:classloading}
> 	at github.pitbox46.hiddennames.ServerEvents.onServerStarting(ServerEvents.java:25) ~[hiddennames-1.20.1-1.0.2.jar%23205!/:1.20.1-1.0.2] {re:classloading}
> 	at github.pitbox46.hiddennames.__ServerEvents_onServerStarting_ServerStartingEvent.invoke(.dynamic) ~[hiddennames-1.20.1-1.0.2.jar%23205!/:1.20.1-1.0.2] {re:classloading,pl:eventbus:B}
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
> 	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:110) ~[forge-1.20.1-47.2.20-universal.jar%23218!/:?] {re:mixin,re:classloading}
> 	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:201) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
> [084月2024 00:01:48.053] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID c268954c-79b6-4278-9b30-6c544585e577
> [084月2024 00:01:48.056] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: E:\MC\[1.20.1SEVER]\[1.20.1SEVER]\.\crash-reports\crash-2024-04-08_00.01.48-server.txt
> [084月2024 00:01:48.056] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server

**Comment by MechRW** [comment]
https://github.com/IzzelAliz/Arclight

a core mix mod and plugins made by chinese people for higher level of mc

**Comment by pitbox46** [comment]
How exactly are you inputting the characters? Chinese characters should be UTF-8. Could you send me the `hiddennames/data.json` *before* the crash occurs and it resets?

**Comment by MechRW** [comment]
The setname instruction used within the server
i just used Chinese，man，like“艺术家”。maybe UTF-8 ,（idk what is for UTF-16）
![image](https://github.com/pitbox46/HiddenNames/assets/162135883/b59b267c-cb66-4a17-97b9-9e2da092fe05)
（i used English now）
I used English quotation marks, which means typing a string.
Your mod may indeed have coding issues, but it doesn't have encoding libraries for UTF-8 and UTF-16.
I don't think I need to send it to you anymore,
It is indeed a matter of Chinese. 
I don't know how Japanese and Russian will work, I'm not very confident in trying them out.

**Comment by pitbox46** [comment]
Okay, I've been able to replicate the issue in Japanese. It's not an issue for the 1.20.4 Neoforged release, which is very odd since they should be very similar. I figure it out and make a fix for you soon

**Comment by MechRW** [comment]
thanks,man

**Comment by pitbox46** [comment]
Fixed with commit https://github.com/pitbox46/HiddenNames/commit/c5e0498d18c3c336c7489e6bcad266660280367e

EDIT: Note that the names will be messed up in the logs. I'm not exactly sure why, I'm pretty confident that this is a Minecraft thing. It looks like by 1.20.4, they fixed the issue to allow UTF-8 encoding

**Comment by MechRW** [comment]
thanks for your works!
but where can i download this fix ver mod?
I'm not particularly familiar with how to use github yet

**Comment by pitbox46** [comment]
@MechRW You can download it from Curseforge https://legacy.curseforge.com/minecraft/mc-mods/hidden-names/files/5246548
