### ISSUE TITLE
data.json reset on Minecraft1.18.2

### ISSUE THREAD

**Issue by light-lgt** [pitbox46/HiddenNames#9]
It always reset data.json when data.json has any Chinese.I think the cause is data.json used ANSI encoding.Chinese does not work on ANSI encoding.Can you fix it?

**Comment by pitbox46** [comment]
Hello! I fixed it on 1.20.1, but I didn't backport it for some reason. I will let you know when I release the fix.

**Comment by pitbox46** [comment]
New version is being uploaded to curseforge!

**Comment by light-lgt** [comment]
Thank you.You are very 牛逼
